# 워크플로우 이름
name: API News and Save to DynamoDB

# 실행 조건: main 브랜치에 코드가 푸시되거나, 매일 오전 9시(UTC)에 자동 실행
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/20 * * * *' # 한국 시간 오후 6시

# 실행할 작업
jobs:
  crawl-and-save:
    runs-on: ubuntu-latest # 실행 환경

    steps:
    # 1. 레포지토리의 코드를 가져옵니다.
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 파이썬 환경을 설정합니다.
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. requirements.txt 파일에 명시된 라이브러리들을 설치합니다.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. AWS 자격 증명을 설정합니다. (GitHub Secrets 사용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # 5. 최종 파이썬 스크립트를 실행합니다. (Naver API 키도 Secrets에서 가져와 환경 변수로 주입)
    - name: Run Python script
      env:
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
      run: python your_script_name.py # 실제 스크립트 파일명으로 변경